spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Dragon204_dima
    url: jdbc:mysql://localhost:3306/mydb?createDatabaseIfNotExist=true
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
